network: 'Alexnet'
multigpu: False
num_classes: 40
data_dir: '/state/partition/zdzhu/'
epochs: 40
batch_size: 128
num_workers: 8
learning_rate: 0.001
weight_decay: 0.0005
milestones: []
gamma: 0.1
print_frequency: 200