network: 'VGG'
layers: 16
multigpu: False
num_classes: 40
data_dir: '/state/partition/zdzhu/'
epochs: 20
batch_size: 64
num_workers: 8
learning_rate: 0.0001
weight_decay: 0.01
milestones: []
gamma: 0.1
print_frequency: 500