network: 'alexnet'
multigpu: False
num_classes: 40
data_dir: '/state/partition/zdzhu/'
epochs: 50
batch_size: 128
num_workers: 8
learning_rate: 0.001
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_eps: 0.000001
milestones: [15, 40]
gamma: 0.2